### ISSUE TITLE
bug: It seems that the YML must include the volunteer section, otherwise the build will fail.

### ISSUE THREAD

**Issue by shuiRong** [yamlresume/yamlresume#14]
## Description

It seems that the YML must include the volunteer content, otherwise the build will fail.

## To Reproduce

1. `yamlresume new`
2. open the resume.yml and remove the whole volunteer section:
```yaml
  volunteer:
    - organization: USC Computer Science and Engineering Society
      url: https://www.usccsesociety.org/
      position: Tech Mentor
      startDate: Sep 2015
      endDate: Jul 2023
      summary: |
        - Volunteered as a Tech Mentor at USC Computer Science and Engineering Society
        - Provided guidance and assistance to fellow students in their technical projects and coursework
        - Assisted in organizing workshops, coding competitions, and networking events for the society members
        - Contributed to fostering a collaborative and supportive environment within the student community
```
4. `yamlresume build resume.yml`
### Actual Behavior

`ERROR  Cannot read properties of undefined (reading 'forEach')`

### Expected Behavior

Successfully built the resume.

### Desktop

- OS: macOS
- Browser: Arc
- Version: 1.94.0 (62506)

## Additional Context

It seems that somewhere requires the volunteer field to be present — not sure if this is a bug or a feature. This doesn’t seem reasonable, as not many people have volunteer experience.

Also, deleting other sections results in the same error.

**Comment by xiaohanyu** [comment]
For the time being the workaround is to set unnecessary sections to `[]`, i.e, `volunteer: []`, this would lead to a blank volunteer section in the final PDF output.

But yeah you're right, I should make non-core sections optional. This is a valid catch.

**Comment by xiaohanyu** [comment]
I am trying to integrate a solid [schema check solution](https://github.com/yamlresume/yamlresume/issues/10) for resume input, so for any input, it must first pass the schema check before transforming YAML to LaTeX. 

Stay tuned.

**Comment by xiaohanyu** [comment]
Fixed, release a new patch version `0.3.1`.

Now a working example with only core sections:

```yml
---
content:
  basics:
    name: Andy Dufresne
    headline: Headed for the Pacific
    phone: "(213) 555-9876"
    email: hi@ppresume.com
    url: https://ppresume.com/gallery
    # All summary fields supports a limited rich text capabilities in markdown
    # syntax:
    #
    # - bold, (e.g, `**bold**`)
    # - italic, (e.g, `*italic*`)
    # - ordered list, unordored list and nested sub list
    # - links (e.g. `[link](https://ppresume.com)`)
    summary: |
      - Computer Science major with strong foundation in data structures, algorithms, and software development
      - Pixel perfect full stack web developer, specialised in creating high-quality, visually appealing websites
      - Experiened in databases (SQL, NoSQL), familiar with server-side technologies (Node.js, Express, etc.)
      - Team player, with detail-oriented mindset and a keen eye for design and user experiences
  location:
    address: 123 Main Street
    city: Sacramento
    region: California
    country: United States
    postalCode: "95814"
  profiles:
    - network: Line
      url: https://line.com/PPResumeX
      username: PPResumeX
    - network: Twitter
      url: https://twitter.com/PPResumeX
      username: PPResumeX
  education:
    - institution: University of Southern California
      url: https://www.cs.usc.edu/
      # Valid degree options:
      #
      # - 'Middle School'
      # - 'High School'
      # - 'Diploma'
      # - 'Associate'
      # - 'Bachelor'
      # - 'Master'
      # - 'Doctor'
      degree: Bachelor
      area: Computer Engineering and Computer Science
      score: "3.8"
      # Should be a valid date string that can be parsed by `new Date(dateStr)`
      # in JavaScript, eg. '2020-01', '2020-02-03', 'Jul 1, 2023' etc.
      #
      # The date part would be removed in the final output as most of the time
      # people won't really care about the exact date for your working
      # experience or education background, etc.
      # ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
      startDate: Sep 1, 2016
      # Leave endDate blank to indicate "Present"
      endDate: Jul 1, 2020
      courses:
        - Discrete Methods in Computer Science
        - Programming Language Concepts
        - Data Structures and Object-Oriented Design
        - Operating Systems
        - Computer Architecture
        - Database Systems
        - Computer Networking
        - Introduction to the Theory of Computing
      summary: |
        - Developed proficiency in programming languages such as Java, C++, and Python
        - Gained hands-on experience in software development through various projects and assignments
        - Strong communication and teamwork skills acquired through group projects and presentations
  work:
    - name: PPResume
      url: https://ppresume.com
      startDate: Dec 1, 2022
      endDate: ""
      position: Senior Software Engineer
      summary: |
        - Developed and implemented efficient and scalable code, ensuring high-quality and maintainable web applications
        - Collaborated with cross-functional teams to gather project requirements and translate them into technical solutions
        - Conducted thorough testing and debugging to identify and resolve any issues or bugs in the software
        - Actively participated in code reviews, providing valuable feedback to improve code quality and adherence to best practices
        - Mentored and guided junior developers, fostering a collaborative and growth-oriented team environment
      keywords:
        - Scalibility
        - Growth
        - Quality
        - Mentorship
    - name: PPResume
      url: https://ppresume.com
      startDate: Sep 1, 2020
      endDate: Dec 1, 2022
      position: Software Engineer
      summary: |
        - Created reusable React components to ensure code efficiency and maintainability
        - Integrated with RESTful APIs to fetch and display dynamic data on the frontend
        - Implemented client-side routing using React Router for smooth navigation between pages
        - Actively participated in Agile development methodologies, attending daily stand-up meetings and sprint planning sessions
      keywords:
        - RESTful
        - React
        - Agile

layout:
  locale:
    # Use `yamlresume languages list` to get the list of supported languages
    language: en
  margins:
    top: 2.5cm
    left: 1.5cm
    right: 1.5cm
    bottom: 2.5cm
  page:
    showPageNumbers: true
  # Use `yamlresume templates list` to get the list of available templates
  template: moderncv-banking
  typography:
    # LaTeX engine only supports 10pt, 11pt, and 12pt
    fontSize: 11pt
```

Output:

![Image](https://github.com/user-attachments/assets/dfc5adcd-fa9a-4fe2-802f-ad58c15794f5)
