### ISSUE TITLE
bug: throw ERROR  when the summary in the section of education is blank

### ISSUE THREAD

**Issue by koo6666** [yamlresume/yamlresume#18]
## Description

 throw ERROR  Cannot read properties of undefined (reading 'trim') 

## To Reproduce

```yaml
  education:
    - institution: xxxxx
      url: xxxxxxxxxxxxxxx
      # Valid degree options:
      #
      # - 'Middle School'
      # - 'High School'
      # - 'Diploma'
      # - 'Associate'
      # - 'Bachelor'
      # - 'Master'
      # - 'Doctor'
      degree: xxxxx
      area: xxxxx
      score: 
      # Should be a valid date string that can be parsed by `new Date(dateStr)`
      # in JavaScript, eg. '2020-01', '2020-02-03', 'Jul 1, 2023' etc.
      #
      # The date part would be removed in the final output as most of the time
      # people won't really care about the exact date for your working
      # experience or education background, etc.
      # ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
      startDate: xxxxx
      # Leave endDate blank to indicate "Present"
      endDate: xxxxx
      courses: []
      summary: ''          <=  here!
```
### Actual Behavior

 throw ERROR  Cannot read properties of undefined (reading 'trim') 

### Expected Behavior

successfully output pdf and without the summary section in the section of education
